Guard against missing clearLine/cursorTo
Previously got the following deploying atom:

```
Running "download-atom-shell" task
Fatal error: Object #<Socket> has no method 'clearLine'
Command /bin/sh failed with exit code 3
```